# Generated by Django 6.0.6 on 2026-06-14 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quantity_changed",
                    models.IntegerField(
                        help_text="Positive for incoming, negative for outgoing."
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("RESTOCK", "New Shipment Arrival"),
                            ("RETURNS", "Customer Return Refund"),
                            ("CORRECTION", "Manual Audit Adjustment"),
                            ("ORDER_DEDUCTION", "Fulfillment Allocation"),
                            ("TIMEOUT_REFUND", "Checkout Session Expiration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "reference_order_id",
                    models.UUIDField(
                        blank=True,
                        help_text="The original purchase invoice ID if applicable.",
                        null=True,
                    ),
                ),
                (
                    "audit_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Stores event-specific context like return_slip_id or admin data.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_logs",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "market_inventory_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
