from django.db import models
from apps.orders.models import Order
from apps.core.models import AuditModel


class TransactionStatus(models.TextChoices):
    PENDING = "PENDING", "Pending"
    SUCCESS = "SUCCESS", "Success"
    FAILED = "FAILED", "Failed"


class PaymentGateway(models.TextChoices):
    RAZORPAY = "RAZORPAY", "Razorpay"
    STRIPE = "STRIPE", "Stripe"
    PAYPAL = "PAYPAL", "PayPal"
    CASH_ON_DELIVERY = "COD", "Cash On Delivery"


class Transaction(AuditModel):
    """
    CNY 💳 IMMUTABLE FINANCIAL AUDIT LEDGER:
    Tracks every distinct payment payload intent across ANY merchant provider.
    Inherits robust audit metrics, UUID primary keys, and soft-delete states from AuditModel.
    """
    # 🔗 Core Relationship
    order = models.ForeignKey(Order, on_delete=models.PROTECT, related_name="transactions")
    
    # 🏁 Polymorphic Gateway Mappings
    gateway = models.CharField(
        max_length=20, 
        choices=PaymentGateway.choices, 
        default=PaymentGateway.RAZORPAY
    )
    
    # 🔑 Generalized Gateway Tracking IDs
    gateway_order_id = models.CharField(
        max_length=150, 
        unique=True, 
        db_index=True, 
        null=True, 
        blank=True,
        help_text="The Order/Intent ID generated by the merchant provider (e.g., rzp_order_xxx or pi_xxx)"
    )
    gateway_transaction_id = models.CharField(
        max_length=150, 
        unique=True, 
        null=True, 
        blank=True,
        help_text="The actual capture/payment reference identifier (e.g., rzp_payment_xxx or ch_xxx)"
    )
    gateway_signature = models.TextField(
        null=True, 
        blank=True,
        help_text="The security hash or verification payload delivered by the provider webhook"
    )
    
    # 💰 Financial Data Matrix
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(
        max_length=15, 
        choices=TransactionStatus.choices, 
        default=TransactionStatus.PENDING
    )
    
    # 📋 Incident Tracking & Snapshots
    error_code = models.CharField(max_length=100, null=True, blank=True)
    error_description = models.TextField(null=True, blank=True)
    raw_response_snapshot = models.JSONField(default=dict, blank=True)

    class Meta:
        db_table = "market_transactions"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Txn {self.id} - Provider: {self.gateway} - Status: {self.status}"