# Generated by Django 6.0.6 on 2026-06-14 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("RAZORPAY", "Razorpay"),
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                            ("COD", "Cash On Delivery"),
                        ],
                        default="RAZORPAY",
                        max_length=20,
                    ),
                ),
                (
                    "gateway_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The Order/Intent ID generated by the merchant provider (e.g., rzp_order_xxx or pi_xxx)",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="The actual capture/payment reference identifier (e.g., rzp_payment_xxx or ch_xxx)",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "gateway_signature",
                    models.TextField(
                        blank=True,
                        help_text="The security hash or verification payload delivered by the provider webhook",
                        null=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("error_description", models.TextField(blank=True, null=True)),
                ("raw_response_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "market_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
