# Generated by Django 6.0.6 on 2026-06-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_address"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                fields=("user", "address_type"), name="unique_user_address_type"
            ),
        ),
    ]
